name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Git LFS
      run: |
        sudo apt-get install git-lfs
        git lfs install

    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          xvfb \
          xclip

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest

    - name: Verify database file
      run: |
        ls -la database/
        if [ -f "database/languageLearningDatabase.db" ]; then
          echo "Database file exists"
          du -h database/languageLearningDatabase.db
        else
          echo "Database file does not exist"
          exit 1
        fi

    - name: Run tests
      run: |
        xvfb-run -a pytest
